trigger:
  - main
  - develop

parameters:
  - name: piralCliVersion
    displayName: Piral CLI Version
    type: string
    default: "next"

strategy:
  matrix:
    linux_node_14:
      imageName: "ubuntu-20.04"
      nodeVersion: 14.x
    linux_node_16:
      imageName: "ubuntu-20.04"
      nodeVersion: 16.x
    linux_node_18:
      imageName: "ubuntu-20.04"
      nodeVersion: 18.x
    linux_node_20:
      imageName: "ubuntu-20.04"
      nodeVersion: 20.x
    windows_node_14:
      imageName: "windows-2019"
      nodeVersion: 14.x
    windows_node_20:
      imageName: "windows-2019"
      nodeVersion: 20.x
    macos_node_14:
      imageName: "macOS-11"
      nodeVersion: 14.x
    macos_node_20:
      imageName: "macOS-11"
      nodeVersion: 20.x

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(nodeVersion)
    displayName: "Install Node.js"

  - script: npm install --legacy-peer-deps
    displayName: "Setup Tests"

  - script: npm test
    continueOnError: true
    displayName: "Run Tests"
    env:
      CLI_VERSION: ${{ parameters.piralCliVersion }}

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "dist/junit*.xml"
      mergeTestResults: true
