trigger:
  - main
  - develop

parameters:
  - name: piralCliVersion
    displayName: Piral CLI Version
    type: string
    default: "next"

strategy:
  matrix:
    linux_node_16:
      imageName: "ubuntu-20.04"
      nodeVersion: 16.x
      cleanup: "no"
    linux_node_20:
      imageName: "ubuntu-20.04"
      nodeVersion: 20.x
      cleanup: "no"
    linux_node_21:
      imageName: "ubuntu-20.04"
      nodeVersion: 21.x
      cleanup: "no"
    windows_node_16:
      imageName: "windows-2019"
      nodeVersion: 16.x
      cleanup: "yes"
    windows_node_20:
      imageName: "windows-2019"
      nodeVersion: 20.x
      cleanup: "yes"
    macos_node_16:
      imageName: "macOS-11"
      nodeVersion: 16.x
      cleanup: "no"
    macos_node_20:
      imageName: "macOS-11"
      nodeVersion: 20.x
      cleanup: "no"

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(nodeVersion)
    displayName: "Install Node.js"

  - script: npm install --legacy-peer-deps
    displayName: "Setup Tests"

  - script: npm test
    continueOnError: true
    displayName: "Run Tests"
    env:
      CLI_VERSION: ${{ parameters.piralCliVersion }}
      CLEANUP: $(cleanup)

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "dist/junit*.xml"
      mergeTestResults: true
